// src/app/part/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { faGithub } from '@fortawesome/free-brands-svg-icons/faGithub';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {
  faGithub = faGithub;

  constructor() {
  }

  ngOnInit(): void {
  }

}

<footer class="bd-footer p-3 p-md-5 mt-5 bg-white shadow-sm text-center text-sm-start">
  <div class="container">
    <ul class="bd-footer-links ps-0 mb-3">
      <li class="d-inline-block">
        <a href="https://github.com/cothema/tax-map" rel="noreferrer">
          <fa-icon [icon]="faGithub"></fa-icon>&nbsp;
          GitHub
        </a>
      </li>
    </ul>

    <p class="mb-0">
      Code license:&nbsp;
      <a href="https://github.com/cothema/tax-map/main/LICENSE"
         target="_blank"
         rel="license noopener noreferrer">MIT</a>,
      text content:&nbsp;
      <a href="https://creativecommons.org/licenses/by/3.0/"
         target="_blank"
         rel="license noopener noreferrer">CC BY 3.0</a>
    </p>
  </div>
</footer>

// src/components/footer/Footer.tsx
import { faGithub } from "@fortawesome/free-brands-svg-icons/faGithub";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React from "react";
import "./Footer.scss";

function Footer() {
  return (
    <footer className="Footer bd-footer p-3 p-md-5 mt-5 bg-white shadow-sm text-center text-sm-start">
      <div className="container">
        <ul className="bd-footer-links ps-0 mb-3">
          <li className="d-inline-block">
            <a href="https://github.com/cothema/tax-map" rel="noreferrer">
              <FontAwesomeIcon icon={faGithub}/>&nbsp;
              GitHub
            </a>
          </li>
        </ul>

        <p className="mb-0">
          Code license:&nbsp;
          <a href="https://github.com/cothema/tax-map/main/LICENSE"
             target="_blank"
             rel="license noopener noreferrer">MIT</a>,
          text content:&nbsp;
          <a href="https://creativecommons.org/licenses/by/3.0/"
             target="_blank"
             rel="license noopener noreferrer">CC BY 3.0</a>
        </p>
      </div>
    </footer>
  );
}

export default Footer;
